version: 2

models:
  - name: stg_customers
    description: One unique customer per row
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: One order per customer
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values:
                - placed
                - shipped
                - completed
                - return_pending
                - returned
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
  - name: stg_payments
    description: One purchase per order
    columns:
      - name: payment_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: order_id
        description: Order the payment is associated with
        tests:
          - not_null
          - relationships:
              field: order_id
              to: ref('stg_orders')
      - name: payment_method
        description: Method of payment
        tests:
          - accepted_values:
              values:
                - credit_card
                - coupon
                - bank_transfer
                - gift_card
      - name: status
        description: Status of the payment
        tests:
          - accepted_values:
              values:
                - success
                - fail
