version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: jaffle_shop
      tables:
          - name: customers
            description: Raw customer data
            columns:
              - name: id
                tests:
                  - unique
                  - not_null
          - name: orders
            description: Raw order data
            columns:
              - name: id
                tests:
                  - unique
                  - not_null
            loaded_at_field: _etl_loaded_at # timestamp field to check for freshness
            freshness: # freshness configuration
              warn_after:
                count: 12
                period: hour
              error_after:
                count: 24
                period: hour
    - name: stripe
      description: Raw Stripe payment data
      database: raw
      schema: stripe
      tables:
        - name: payment
          description: Stripe payment data
          columns:
            - name: id
              tests:
                - unique
                - not_null
          loaded_at_field: _batched_at
          freshness:
            warn_after:
              count: 12
              period: hour
            error_after:
              count: 24
              period: hour
